Implement character play time
MeikelLP/quantum-core-x pull request #118
Opened 2024-05-10 13:28 UTC by WoozChucky

2024-05-10 21:29 UTC, MeikelLP commented
What about persisting it in the DB? :)

2024-05-10 21:38 UTC, WoozChucky commented
> What about persisting it in the DB? :)

Hmm, `await _world.DespawnPlayerAsync(context.Player);` should take care of it both in `SelectPhaseHandler` and `LogoutCommand` according to the in-game test and debug that I've made. Did I missunderstood anything ?

2024-05-11 06:32 UTC, MeikelLP commented
You have to adjust the function which maps `PlayerData` to `Player` (Entity) :)

2024-05-11 13:35 UTC, WoozChucky commented
> You have to adjust the function which maps `PlayerData` to `Player` (Entity) :)

I'm guessing that would be in DbPlayerRepository.cs: line 76, but it is already done. Or are you refering to another location? I tried to find it 

```c#
public async Task SetPlayerAsync(PlayerData data)
    {
        var entity = await _db.Players.FirstOrDefaultAsync(x => x.Id == data.Id);
        if (entity is null) return;

        entity.Empire = data.Empire;
        entity.PlayerClass = data.PlayerClass;
        entity.SkillGroup = data.SkillGroup;
        entity.PlayTime = data.PlayTime;       // it was already mapped before my pr
        entity.Level = data.Level;
        entity.Experience = data.Experience;
        entity.Gold = data.Gold;
        entity.St = data.St;
        entity.Ht = data.Ht;
        entity.Dx = data.Dx;
        entity.Iq = data.Iq;
        entity.PositionX = data.PositionX;
        entity.PositionY = data.PositionY;
        entity.Health = data.Health;
        entity.Mana = data.Mana;
        entity.Stamina = data.Stamina;
        entity.BodyPart = data.BodyPart;
        entity.HairPart = data.HairPart;
        entity.Name = data.Name;
        entity.GivenStatusPoints = data.GivenStatusPoints;
        entity.AvailableStatusPoints = data.AvailableStatusPoints;

        await _db.SaveChangesAsync();
    }
```

2024-05-11 22:12 UTC, MeikelLP commented
What about a forced disconnect or a disconnect because connection is lost?

2024-05-11 22:13 UTC, MeikelLP commented
> > You have to adjust the function which maps `PlayerData` to `Player` (Entity) :)
> 
> I'm guessing that would be in DbPlayerRepository.cs: line 76, but it is already done. Or are you refering to another location? I tried to find it
> 
> ```cs
>     public async Task SetPlayerAsync(PlayerData data)
>     {
>         var entity = await _db.Players.FirstOrDefaultAsync(x => x.Id == data.Id);
>         if (entity is null) return;
> 
>         entity.Empire = data.Empire;
>         entity.PlayerClass = data.PlayerClass;
>         entity.SkillGroup = data.SkillGroup;
>         entity.PlayTime = data.PlayTime;       // it was already mapped before my pr
>         entity.Level = data.Level;
>         entity.Experience = data.Experience;
>         entity.Gold = data.Gold;
>         entity.St = data.St;
>         entity.Ht = data.Ht;
>         entity.Dx = data.Dx;
>         entity.Iq = data.Iq;
>         entity.PositionX = data.PositionX;
>         entity.PositionY = data.PositionY;
>         entity.Health = data.Health;
>         entity.Mana = data.Mana;
>         entity.Stamina = data.Stamina;
>         entity.BodyPart = data.BodyPart;
>         entity.HairPart = data.HairPart;
>         entity.Name = data.Name;
>         entity.GivenStatusPoints = data.GivenStatusPoints;
>         entity.AvailableStatusPoints = data.AvailableStatusPoints;
> 
>         await _db.SaveChangesAsync();
>     }
> ```

Oh then nevermind :)

2024-05-12 03:29 UTC, WoozChucky commented
> What about a forced disconnect or a disconnect because connection is lost?

Implemented the code for when the connection is lost/dropped.
- Not sure if I like my own approach here because I had to change the public api of `Connection`, it's not a breaking change with existing code but still, if you have a better idea feel free to share your thoughts! :) 

In case of a forced disconnect (from either the server, or player exiting via logout/quit) the world de-spawn should take care of it.

2024-05-12 15:45 UTC, MeikelLP commented
Sorry, another thing I thought about:
How about we track the players time in ms (long) and just display the number in minutes. This way we are much more accurate. Imagine how many minutes u lose just because of logging in and out

2024-05-12 16:58 UTC, WoozChucky commented
> Sorry, another thing I thought about: How about we track the players time in ms (long) and just display the number in minutes. This way we are much more accurate. Imagine how many minutes u lose just because of logging in and out

Agreed!

2024-05-13 21:49 UTC, MeikelLP commented on src/Executables/Game/Extensions/PaketExtensions.cs
> +            Playtime = player.PlayTime == 0 ? 0 : (uint) player.PlayTime / 60000, // Milliseconds to minutes
Maybe a more readable approach would be `TimeSpan.FromMiliSeconds(player.PlayTime).TotalMinutes` but it's up to you :)

2024-05-13 21:50 UTC, MeikelLP commented on src/Executables/Game/World/Entities/PlayerEntity.cs
> +                    return Player.PlayTime == 0 ? 0 : (uint) Player.PlayTime / 60000; // milliseconds to minutes
Same as above

2024-05-13 21:50 UTC, MeikelLP requested changes

2024-05-13 21:50 UTC, MeikelLP commented on src/Executables/Game/World/Entities/PlayerEntity.cs
> +            //var minutes = sessionTimeMillis / 60000; // milliseconds to minutes
Dead code?

2024-05-14 14:00 UTC, MeikelLP commented
Pipeline is still failing. Probably due to changes in the migrations

2024-05-14 17:05 UTC, WoozChucky commented
> Pipeline is still failing. Probably due to changes in the migrations

Yep that was exactly it, plus a test that was failing due to player fake data giving a overflow in `TimeSpan` conversion of `PlayTime`.

2024-05-14 17:18 UTC, MeikelLP approved these changes

2024-05-14 17:19 UTC, merged